defaults: &defaults
  working_directory: ~/reg-suit
  docker:
    - image: quramy/node-nightmare
      environment:
        DISPLAY: ":99"

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Bootstrap packages
          command: yarn run bootstrap
      - run:
          name: Lint
          command: yarn run lint
      - run:
          name: Test
          command: |
            xvfbd start
            yarn run test
            xvfbd stop
      - run:
          name: Regression using gh-io components
          command: |
            cd packages/reg-suit-toppage
            npm run regression

  patch_release:
    <<: *defaults
    steps:
      - add-ssh-keys:
          fingerprints:
            - "9b:4a:d1:c6:ff:b7:49:b7:b7:bf:24:fb:b1:1e:bc:a6"
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Bootstrap packages
          command: yarn run bootstrap
      - run:
          name: Setup git
          command: |
            git config --global user.email "yosuke.kurami@gmail.com"
            git config --global user.name "Quramy"
      - run:
          name: Login npm
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
            npm whoami
      - run:
          name: Deploy services
          command: |
            yarn run deploy
      - run:
          name: Publish to npm
          command: |
            yarn run lerna publish -- --yes --cd-version="patch"

  minor_release:
    <<: *defaults
    steps:
      - add-ssh-keys:
          fingerprints:
            - "9b:4a:d1:c6:ff:b7:49:b7:b7:bf:24:fb:b1:1e:bc:a6"
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Bootstrap packages
          command: yarn run bootstrap
      - run:
          name: Setup git
          command: |
            git config --global user.email "yosuke.kurami@gmail.com"
            git config --global user.name "Quramy"
      - run:
          name: Login npm
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
            npm whoami
      - run:
          name: Deploy services
          command: |
            cd packages/reg-gh-app
            ./node_modules/.bin/sls config credentials --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY} 
            cd ../../
            yarn run deploy
      - run:
          name: Publish to npm
          command: |
            yarn run lerna publish -- --yes --cd-version="minor"

  deply_service:
    <<: *defaults
    steps:
      - add-ssh-keys:
          fingerprints:
            - "9b:4a:d1:c6:ff:b7:49:b7:b7:bf:24:fb:b1:1e:bc:a6"
      - run:
          name: Setup git
          command: |
            git config --global user.email "yosuke.kurami@gmail.com"
            git config --global user.name "Quramy"
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Bootstrap packages
          command: yarn run bootstrap
      - run:
          name: Deploy services
          command: |
            cd packages/reg-gh-app
            ./node_modules/.bin/sls config credentials --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY} 
            cd ../../
            yarn run deploy

workflows:
  version: 2
  reg_build_pipeline:
    jobs:
      - build
      - confirm_patch:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - build
      - confirm_minor:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - build
      - confirm_deploy_services:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - build
      - patch_release:
          filters:
            branches:
              only: master
          requires:
            - confirm_patch
      - minor_release:
          filters:
            branches:
              only: master
          requires:
            - confirm_minor
      - deply_service:
          filters:
            branches:
              only: master
          requires:
            - confirm_deploy_services
          
